name: Dispatcher

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which workflow do we need to dispatch'
        required: true
        type: choice
        options:
          - master
          - staging
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger specific workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt install gh
          if [[ "${{ github.event.inputs.branch }}" == "master" ]]; then
            gh workflow run ci.yml
          elif [[ "${{ github.event.inputs.branch }}" == "staging" ]]; then
            gh workflow run ci-staging.yml
          fi
